// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: audio_like.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAudioLike = `-- name: CreateAudioLike :one
INSERT INTO audio_likes(
  id,
  audio_id, 
  user_id,
  created_at
) VALUES ($1, $2, $3, $4) 
RETURNING id, created_at, user_id, audio_id
`

type CreateAudioLikeParams struct {
	ID        uuid.UUID
	AudioID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateAudioLike(ctx context.Context, arg CreateAudioLikeParams) (AudioLike, error) {
	row := q.db.QueryRowContext(ctx, createAudioLike,
		arg.ID,
		arg.AudioID,
		arg.UserID,
		arg.CreatedAt,
	)
	var i AudioLike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.AudioID,
	)
	return i, err
}

const deleteAudioLike = `-- name: DeleteAudioLike :exec
DELETE FROM audio_likes 
  WHERE audio_id = $1 AND user_id = $2
`

type DeleteAudioLikeParams struct {
	AudioID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteAudioLike(ctx context.Context, arg DeleteAudioLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAudioLike, arg.AudioID, arg.UserID)
	return err
}

const getAudioLikesByUserID = `-- name: GetAudioLikesByUserID :many
SELECT id, created_at, user_id, audio_id 
FROM audio_likes 
WHERE user_id = $1::uuid
`

func (q *Queries) GetAudioLikesByUserID(ctx context.Context, userID uuid.UUID) ([]AudioLike, error) {
	rows, err := q.db.QueryContext(ctx, getAudioLikesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudioLike
	for rows.Next() {
		var i AudioLike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.AudioID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAudioLikesByUserIDAndAudioIDs = `-- name: GetAudioLikesByUserIDAndAudioIDs :many
SELECT id, created_at, user_id, audio_id
FROM audio_likes
WHERE user_id = $1::uuid AND 
  audio_id = ANY($2::uuid[])
`

type GetAudioLikesByUserIDAndAudioIDsParams struct {
	UserID   uuid.UUID
	AudioIds []uuid.UUID
}

func (q *Queries) GetAudioLikesByUserIDAndAudioIDs(ctx context.Context, arg GetAudioLikesByUserIDAndAudioIDsParams) ([]AudioLike, error) {
	rows, err := q.db.QueryContext(ctx, getAudioLikesByUserIDAndAudioIDs, arg.UserID, pq.Array(arg.AudioIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudioLike
	for rows.Next() {
		var i AudioLike
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.AudioID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
