// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Audio struct {
	ID        uuid.UUID
	Title     sql.NullString
	Author    sql.NullString
	Duration  sql.NullInt32
	Path      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.NullUUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      sql.NullString
	Email     sql.NullString
}
