// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT COUNT(*) FROM users WHERE email = $1
`

func (q *Queries) CountUsersByEmail(ctx context.Context, email sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, created_at, name, email, auth_provider, password_hash)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, created_at, name, email, auth_provider, password_hash
`

type CreateUserParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	Name         sql.NullString
	Email        sql.NullString
	AuthProvider AuthProvider
	PasswordHash sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.Name,
		arg.Email,
		arg.AuthProvider,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.AuthProvider,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, name, email, auth_provider, password_hash FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.AuthProvider,
		&i.PasswordHash,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, created_at, name, email, auth_provider, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.AuthProvider,
		&i.PasswordHash,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :exec
SELECT id, created_at, name, email, auth_provider, password_hash FROM "users"
`

func (q *Queries) GetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getUsers)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($1, name)
WHERE id = $2
RETURNING id, created_at, name, email, auth_provider, password_hash
`

type UpdateUserParams struct {
	Name sql.NullString
	ID   uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Name, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.AuthProvider,
		&i.PasswordHash,
	)
	return i, err
}
