// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user.sql

package database

import (
	"context"
)

const getUsers = `-- name: GetUsers :exec
select id, created_at, updated_at, name FROM "users"
`

func (q *Queries) GetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getUsers)
	return err
}
