// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_audio.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countUserAudio = `-- name: CountUserAudio :one
SELECT COUNT(1) 
FROM user_audios 
WHERE user_id = $1
  AND audio_id = $2
`

type CountUserAudioParams struct {
	UserID  uuid.UUID
	AudioID uuid.UUID
}

func (q *Queries) CountUserAudio(ctx context.Context, arg CountUserAudioParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAudio, arg.UserID, arg.AudioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAudioByLocalID = `-- name: CountUserAudioByLocalID :one
SELECT COUNT(*) FROM user_audios 
  INNER JOIN audios ON user_audios.audio_id = audios.id 
  WHERE user_audios.user_id = $1 AND audios.local_id = $2
`

type CountUserAudioByLocalIDParams struct {
	UserID  uuid.UUID
	LocalID sql.NullString
}

func (q *Queries) CountUserAudioByLocalID(ctx context.Context, arg CountUserAudioByLocalIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAudioByLocalID, arg.UserID, arg.LocalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAudiosByAudioID = `-- name: CountUserAudiosByAudioID :one
SELECT COUNT(1) FROM user_audios WHERE audio_id = $1
`

func (q *Queries) CountUserAudiosByAudioID(ctx context.Context, audioID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAudiosByAudioID, audioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAudio = `-- name: CreateUserAudio :one
INSERT INTO user_audios(
  id,
  created_at,
  user_id, 
  audio_id
) VALUES ($1,$2,$3,$4) 
RETURNING id, created_at, user_id, audio_id
`

type CreateUserAudioParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UserID    uuid.UUID
	AudioID   uuid.UUID
}

func (q *Queries) CreateUserAudio(ctx context.Context, arg CreateUserAudioParams) (UserAudio, error) {
	row := q.db.QueryRowContext(ctx, createUserAudio,
		arg.ID,
		arg.CreatedAt,
		arg.UserID,
		arg.AudioID,
	)
	var i UserAudio
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.AudioID,
	)
	return i, err
}

const deleteUserAudio = `-- name: DeleteUserAudio :exec
DELETE FROM user_audios WHERE user_id = $1 AND audio_id = $2
`

type DeleteUserAudioParams struct {
	UserID  uuid.UUID
	AudioID uuid.UUID
}

func (q *Queries) DeleteUserAudio(ctx context.Context, arg DeleteUserAudioParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserAudio, arg.UserID, arg.AudioID)
	return err
}

const getUserAudioIDs = `-- name: GetUserAudioIDs :many
SELECT audio_id FROM user_audios WHERE user_id = $1
`

func (q *Queries) GetUserAudioIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getUserAudioIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var audio_id uuid.UUID
		if err := rows.Scan(&audio_id); err != nil {
			return nil, err
		}
		items = append(items, audio_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAudiosByAudioIds = `-- name: GetUserAudiosByAudioIds :many
SELECT user_audios.id, user_audios.created_at, user_audios.user_id, user_audios.audio_id,
  audio_likes.id AS audio_likes_id,
  audio_likes.created_at AS audio_likes_created_at,
  audio_likes.user_id AS audio_likes_user_id,
  audio_likes.audio_id AS audio_likes_audio_id,

  audios.id AS audio_id,
  audios.created_at AS audio_created_at,
  audios.title AS audio_title,
  audios.author AS audio_author,
  audios.duration_ms AS audio_duration_ms,
  audios.path AS audio_path,
  audios.size_bytes AS audio_size_bytes,
  audios.youtube_video_id AS audio_youtube_video_id,
  audios.thumbnail_path AS audio_thumbnail_path,
  audios.spotify_id AS audio_spotify_id,
  audios.thumbnail_url AS audio_thumbnail_url,
  audios.local_id AS audio_local_id
FROM user_audios
INNER JOIN audios ON user_audios.audio_id = audios.id
LEFT JOIN audio_likes ON audio_likes.audio_id = audios.id
WHERE user_audios.user_id = $1 AND audios.id = ANY($2::uuid[])
`

type GetUserAudiosByAudioIdsParams struct {
	UserID   uuid.UUID
	AudioIds []uuid.UUID
}

type GetUserAudiosByAudioIdsRow struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UserID              uuid.UUID
	AudioID             uuid.UUID
	AudioLikesID        uuid.NullUUID
	AudioLikesCreatedAt sql.NullTime
	AudioLikesUserID    uuid.NullUUID
	AudioLikesAudioID   uuid.NullUUID
	AudioID_2           uuid.UUID
	AudioCreatedAt      time.Time
	AudioTitle          sql.NullString
	AudioAuthor         sql.NullString
	AudioDurationMs     sql.NullInt32
	AudioPath           sql.NullString
	AudioSizeBytes      sql.NullInt64
	AudioYoutubeVideoID sql.NullString
	AudioThumbnailPath  sql.NullString
	AudioSpotifyID      sql.NullString
	AudioThumbnailUrl   sql.NullString
	AudioLocalID        sql.NullString
}

func (q *Queries) GetUserAudiosByAudioIds(ctx context.Context, arg GetUserAudiosByAudioIdsParams) ([]GetUserAudiosByAudioIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAudiosByAudioIds, arg.UserID, pq.Array(arg.AudioIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAudiosByAudioIdsRow
	for rows.Next() {
		var i GetUserAudiosByAudioIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.AudioID,
			&i.AudioLikesID,
			&i.AudioLikesCreatedAt,
			&i.AudioLikesUserID,
			&i.AudioLikesAudioID,
			&i.AudioID_2,
			&i.AudioCreatedAt,
			&i.AudioTitle,
			&i.AudioAuthor,
			&i.AudioDurationMs,
			&i.AudioPath,
			&i.AudioSizeBytes,
			&i.AudioYoutubeVideoID,
			&i.AudioThumbnailPath,
			&i.AudioSpotifyID,
			&i.AudioThumbnailUrl,
			&i.AudioLocalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userAudioExistsByYoutubeVideoID = `-- name: UserAudioExistsByYoutubeVideoID :one
SELECT EXISTS(
  SELECT 1 FROM user_audios
    INNER JOIN audios ON user_audios.audio_id = audios.id
    WHERE user_audios.user_id = $1 
      AND audios.youtube_video_id = $2
)
`

type UserAudioExistsByYoutubeVideoIDParams struct {
	UserID         uuid.UUID
	YoutubeVideoID sql.NullString
}

func (q *Queries) UserAudioExistsByYoutubeVideoID(ctx context.Context, arg UserAudioExistsByYoutubeVideoIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userAudioExistsByYoutubeVideoID, arg.UserID, arg.YoutubeVideoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
