version: "3"

volumes:
  sonify_postgres_data:
  local_redis_data:

services:
  # sonify:
  #   build: ./
  #   # network_mode: host
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     sonifydb:
  #       condition: service_healthy
  #   volumes:
  #     - /root/sonifybackendpublic:/app/public

  sonifydb:
    image: postgres:14.5-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=dwagrw21321d2d1d
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=sonify
    volumes:
      - sonify_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  sonifyredis:
      image: redis:7-alpine    
      container_name: sonify_redis
      ports:
        - "6379:6379"
      volumes:
        - local_redis_data:/data
      command: /bin/sh -c "redis-server --requirepass N4Aop37Glf0"

