-- +goose Up

ALTER TABLE playlists
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE artists
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_audios
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE playlist_audios
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE artist_audios
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_playlists
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- +goose Down

ALTER TABLE playlists
  DROP COLUMN created_at;

ALTER TABLE artists
  DROP COLUMN created_at;

ALTER TABLE user_audios
  DROP COLUMN created_at;

ALTER TABLE playlist_audios
  DROP COLUMN created_at;

ALTER TABLE artist_audios
  DROP COLUMN created_at;

ALTER TABLE user_playlists
  DROP COLUMN created_at;
