name: CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: shut down the image
        run: docker-compose down
      - name: remove dangling images
        run: docker image prune --all --force
      - name: rebuild the image
        run: docker-compose build --no-cache
      - name: run the image
        run: docker-compose up -d
    env:
      ENVIRONMENT: ${{ env.ENVIRONMENT }}
      PORT: ${{ env.PORT }}
      DB_URL: ${{ env.DB_URL }}
      POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      POSTGRES_USERNAME: ${{ env.POSTGRES_USERNAME }}
      POSTGRES_DB: ${{ env.POSTGRES_DB }}
      REDIS_PASSWORD: ${{ env.REDIS_PASSWORD }}
      GOOGLE_CLIENT_KEY: ${{ env.GOOGLE_CLIENT_KEY }}
      ACCESS_TOKEN_SECRET: ${{ env.ACCESS_TOKEN_SECRET }}
      ACCESS_TOKEN_EXP_MILLIS: ${{ env.ACCESS_TOKEN_EXP_MILLIS }}
      PUBLIC_DIR: ${{ env.PUBLIC_DIR }}
      SPOTIFY_CLIENT_ID: ${{ env.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ env.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REDIRECT_URI: ${{ env.SPOTIFY_REDIRECT_URI }}
      MAX_UPLOAD_SIZE_BYTES: ${{ env.MAX_UPLOAD_SIZE_BYTES }}
