name: CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: shut down the image
        run: docker-compose down
      - name: remove dangling images
        run: docker image prune --all --force
      - name: rebuild the image
        run: docker-compose build --no-cache
      - name: run the image
        run: docker-compose up -d
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      PORT: ${{ vars.PORT }}
      DB_URL: ${{ vars.DB_URL }}
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_USERNAME: ${{ vars.POSTGRES_USERNAME }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}
      GOOGLE_CLIENT_KEY: ${{ vars.GOOGLE_CLIENT_KEY }}
      ACCESS_TOKEN_SECRET: ${{ vars.ACCESS_TOKEN_SECRET }}
      ACCESS_TOKEN_EXP_MILLIS: ${{ vars.ACCESS_TOKEN_EXP_MILLIS }}
      PUBLIC_DIR: ${{ vars.PUBLIC_DIR }}
      SPOTIFY_CLIENT_ID: ${{ vars.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ vars.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REDIRECT_URI: ${{ vars.SPOTIFY_REDIRECT_URI }}
      MAX_UPLOAD_SIZE_BYTES: ${{ vars.MAX_UPLOAD_SIZE_BYTES }}
