name: CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: shut down the image
        run: docker-compose down
      - name: remove dangling images
        run: docker image prune --all --force
      - name: rebuild the image
        run: docker-compose build --no-cache
      - name: run the image
        run: docker-compose up -d

    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      PORT: ${{ secrets.PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_ADDRESS: ${{ secrets.REDIS_ADDRESS }}
      GOOGLE_CLIENT_KEY: ${{ secrets.GOOGLE_CLIENT_KEY }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      ACCESS_TOKEN_EXP_MILLIS: ${{ secrets.ACCESS_TOKEN_EXP_MILLIS }}
      PUBLIC_DIR: ${{ secrets.PUBLIC_DIR }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
      MAX_UPLOAD_SIZE_BYTES: ${{ secrets.MAX_UPLOAD_SIZE_BYTES }}
